# Generated by Django 3.1.1 on 2020-10-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_bank', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='language',
        ),
        migrations.RemoveField(
            model_name='bank',
            name='style',
        ),
        migrations.AlterField(
            model_name='bank',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
