# Generated by Django 3.1.1 on 2020-10-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system_bank', '0002_auto_20201015_0852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='title',
            new_name='code',
        ),
    ]
